### ISSUE TITLE
GZIP on POST/PUT requests

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-php#563] opened 2019-07-02 13:47 UTC
https://github.com/algolia/algoliasearch-client-specs-internal/issues/30

**Comment by TomKlotzPro** [comment] 2019-07-08 13:28
cc @aseure [561](https://github.com/algolia/algoliasearch-client-php/issues/561)

**Comment by chloelbn** [comment] 2019-09-10 09:32
Duplicate of https://github.com/algolia/algoliasearch-client-php/issues/561, I'm closing this issue

**Closed by chloelbn** 2019-09-10 09:32 UTC
