### ISSUE TITLE
Where method only allows numbers

### ISSUE THREAD

**Issue by pdellepiane** [algolia/algoliasearch-client-php#587] opened 2019-10-02 06:07 UTC
I'm getting the following error: Invalid syntax for numeric condition

This is because on the "where" comparison is trying to parse an integer and I have a string.

My IDs are tokens so they are a mix of numbers and letters.

Is there a way out of this?

**Comment by chloelbn** [comment] 2019-10-03 08:14
Duplicate of https://github.com/algolia/scout-extended/issues/203

**Closed by chloelbn** 2019-10-03 08:14 UTC
